[tool.poetry]
name = "services"
version = "0.86.2"
description = "Agenta Services (Chat & Completion)"
authors = [
    "Mahmoud Mabrouk <mahmoud@agenta.ai>",
    "Juan Vega <jp@agenta.ai>"
]
package-mode = false

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = "^3.11"

# Agenta SDK
agenta = ">=0.85.0"

# Server
uvicorn = "^0.40"
gunicorn = "^25"

# Traces, Metrics, Logs
structlog = "^25"
newrelic = "^11"

# LiteLLM providers
boto3 = "^1"
google-cloud-aiplatform = "^1"

# Serialization (required by litellm for OpenAI responses)
orjson = "^3"

[tool.poetry.group.dev.dependencies]
watchdog = { extras = ["watchmedo"], version = "^3" }
pytest = "^8"
pytest-asyncio = "^0.21"
