services:
  completion:
    build: .
    volumes:
      - .:/app
      - ../../agenta-cli:/agenta-cli
    environment:
      - AGENTA_UNAUTHORIZED_EXECUTION_ALLOWED=True
      - AGENTA_HOST=http://host.docker.internal
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - COHERE_API_KEY=${COHERE_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - ANYSCALE_API_KEY=${ANYSCALE_API_KEY}
      - PERPLEXITYAI_API_KEY=${PERPLEXITYAI_API_KEY}
      - DEEPINFRA_API_KEY=${DEEPINFRA_API_KEY}
      - TOGETHERAI_API_KEY=${TOGETHERAI_API_KEY}
      - ALEPHALPHA_API_KEY=${ALEPHALPHA_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    networks:
      - agenta-network
    labels:
      - "traefik.http.routers.completion.rule=PathPrefix(`/completion/`)"
      - "traefik.http.routers.completion.entrypoints=web"
      - "traefik.http.middlewares.completion-strip.stripprefix.prefixes=/completion"
      - "traefik.http.middlewares.completion-strip.stripprefix.forceslash=true"
      - "traefik.http.routers.completion.middlewares=completion-strip"
      - "traefik.http.services.completion.loadbalancer.server.port=80"
      - "traefik.http.routers.completion.service=completion"

networks:
  agenta-network:
    external: true
