docker_registry_url="registry:5001"
registry="agentaai"
database_url="sqlite:////db/deploy.db"
redis_url="redis://redis:6379/0"
docker_hub_url="https://hub.docker.com/v2/repositories/{}/{}"
docker_hub_repo_owner="agentaai"
docker_hub_repo_name="templates"
feature_flag="oss"
openai_api_key="value"
ecr_repository="value"
aws_secret_access_key="value"
aws_access_key_id="value"
aws_region="value"