name: Execute Backend tests

on: [pull_request]

jobs:
  continous_integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Start Docker Compose
        run: docker-compose up -d

      - name: Run tests
        run: docker exec agenta-backend-1 pytest

      - name: Stop Docker Compose
        run: docker-compose down