name: Check Python Code - Black
on:
  pull_request:
    paths:
      - "agenta-backend/**"
      - "agenta-cli/**"
      - "examples/**"

jobs:
  linter_name:
    name: runner / black check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
