name: cli commands tests

on:
    pull_request:
        paths:
            - "agenta-backend/**"
            - "agenta-cli/**"

jobs:
    serve-to-oss:
        runs-on: ubuntu-latest
        environment: oss
        steps:
            - name: Check out repository
              uses: actions/checkout@v4

            - name: Set up python
              id: setup-python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.12"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip setuptools
                  pip install poetry
                  cd agenta-cli
                  pip install -e .

            - name: Create .env file
              run: |
                  echo "OPENAI_API_KEY=${{ secrets.NEXT_PUBLIC_OPENAI_API_KEY }}" > .env
              working-directory: examples/baby_name_generator

            - name: Run agenta init
              run: |
                  APP_NAME="gh-cli-$(date +'%y-%m-%d_%H-%M-%S')"
                  cd examples/baby_name_generator
                  agenta init --app_name $APP_NAME --backend_host ${{ secrets.BACKEND_HOST }}
              shell: bash
              continue-on-error: false

            - name: Run agenta variant serve
              run: |
                  cd examples/baby_name_generator
                  agenta variant serve --file_name app.py
              shell: bash
              continue-on-error: false

            - name: Run agenta variant serve with overwrite
              run: |
                  cd examples/baby_name_generator
                  agenta variant serve --file_name app.py --overwrite
              shell: bash
              continue-on-error: false

    serve-to-cloud:
        runs-on: ubuntu-latest
        environment: oss
        steps:
            - name: Check out repository
              uses: actions/checkout@v4

            - name: Set up python
              id: setup-python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.12"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip setuptools
                  pip install poetry
                  cd agenta-cli
                  pip install -e .

            - name: Create .env file
              run: |
                  echo "OPENAI_API_KEY=${{ secrets.NEXT_PUBLIC_OPENAI_API_KEY }}" > .env
              working-directory: examples/baby_name_generator

            - name: Run agenta init
              run: |
                  APP_NAME="gh-cli-$(date +'%y-%m-%d_%H-%M-%S')"
                  cd examples/baby_name_generator
                  AGENTA_API_KEY=${{ secrets.AGENTA_API_KEY }} agenta init --app_name $APP_NAME --backend_host https://cloud.agenta.ai --organisation team
              shell: bash
              continue-on-error: false

            - name: Run agenta variant serve
              run: |
                  cd examples/baby_name_generator
                  agenta variant serve --file_name app.py
              shell: bash
              continue-on-error: false

            - name: Run agenta variant serve with overwrite
              run: |
                  cd examples/baby_name_generator
                  agenta variant serve --file_name app.py --overwrite
              shell: bash
              continue-on-error: false
