name: Build and Publish Docker Images

on: [pull_request]
  # push:
  #   branches:
  #     - main

env:
  BACKEND_IMAGE_NAME: agenta-backend
  BACKEND_DOCKERFILE_PATH: agenta-backend/Dockerfile
  WEB_IMAGE_NAME: agenta-web
  WEB_DOCKERFILE_PATH: agenta-web/prod.Dockerfile
  REPOSITORY_USERNAME: ${{ github.actor }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: .

      - name: Clear Docker build cache
        run: ls

      - name: Build and push backend Docker image
        run: docker build --no-cache -t ${{ env.BACKEND_IMAGE_NAME }} -f ${{ env.BACKEND_DOCKERFILE_PATH }} .

      - name: Build and push web Docker image
        run: docker build --no-cache -t ${{ env.WEB_IMAGE_NAME }} -f ${{ env.WEB_DOCKERFILE_PATH }} .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ env.REPOSITORY_USERNAME }}
          password: ${{ secrets.DOCKER_GITHUB_SECRETS }}

      - name: Push backend Docker image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.repository }}/${{ env.BACKEND_IMAGE_NAME }}
  
      - name: Push web Docker image to GitHub Container Registry
        run: docker push ghcr.io/${{ env.REPOSITORY_USERNAME }}/${{ env.WEB_IMAGE_NAME }}
