name: Build and Publish Docker Images

on: [pull_request]
  # push:
  #   branches:
  #     - main

env:
  BACKEND_IMAGE_NAME: agenta-backend
  BACKEND_DOCKERFILE_PATH: ./agenta-backend/Dockerfile
  WEB_IMAGE_NAME: agenta-web
  WEB_DOCKERFILE_PATH: ./agenta-web/prod.Dockerfile
  REPOSITORY_USERNAME: israelabraham

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clear Docker build cache
        run: docker builder prune --all --force --filter type=exec.cachemount --filter unused-for=24h

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ env.BACKEND_DOCKERFILE_PATH }}
          push: true
          tags: ${{ env.BACKEND_IMAGE_NAME }}:latest

      - name: Build and push web Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ env.WEB_DOCKERFILE_PATH }}
          push: true
          tags: ${{ env.WEB_IMAGE_NAME }}:latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ env.REPOSITORY_USERNAME }}
          password: ${{ secrets.DOCKER_GITHUB_SECRETS }}

      - name: Push backend Docker image to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ env.BACKEND_DOCKERFILE_PATH }}
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ env.BACKEND_IMAGE_NAME }}:${{ github.sha }}

      - name: Push web Docker image to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ env.WEB_DOCKERFILE_PATH }}
          push: true
          tags: ghcr.io/${{ env.REPOSITORY_USERNAME }}/${{ env.WEB_IMAGE_NAME }}:${{ github.sha }}
