name: Execute Frontend tests

on: [pull_request]

jobs:
  cypress:
    runs-on: ubuntu-latest
    environment: oss

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Start Docker Compose
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          wait-on: "http://localhost"
          config-file: ${{ github.workspace }}/agenta-web/cypress.config.ts
          working-directory: agenta-web
        env:
          NEXT_PUBLIC_OPENAI_API_KEY: ${{ secrets.NEXT_PUBLIC_OPENAI_API_KEY }}

      - name: Stop server and database
        run: docker-compose -f "docker-compose.yml" down
        working-directory: ${{ github.workspace }}
