name: Execute Frontend tests

on: push

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Start Docker Compose
        run: docker-compose -f "docker-compose.test.yml" up -d --build

      - name: Install Curl
        run: sudo apt install curl -y

      - name: Wait for Backend Service
        run: |
          while true; do
            if curl -s http://localhost:8000/openapi.json; then
              break
            fi
            sleep 5
          done

      - name: Install dependencies
        run: |
          cd ${{ github.workspace }}/agenta-web/
          npm install

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          config-file: ${{ github.workspace }}/agenta-web/cypress.config.ts
          working-directory: agenta-web
          env: baseApiURL=http://localhost/api,localBaseUrl=http://localhost,OPENAI_API_KEY=
          spec: cypress/e2e/*.cy.ts

      - name: Stop server and database
        run: docker-compose -f "docker-compose.yml" down
        working-directory: ${{ github.workspace }}
