name: Execute Frontend tests

on: push

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Start Docker Compose
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Install dependencies
        run: |
          cd ${{ github.workspace }}/agenta-web/
          npm install

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          config-file: ${{ github.workspace }}/agenta-web/cypress.config.ts
          working-directory: agenta-web

      - name: Stop server and database
        run: docker-compose -f "docker-compose.yml" down
        working-directory: ${{ github.workspace }}
